FROM python:3.12-slim-bookworm

# Set the working directory
WORKDIR /app

COPY . /app

# Install the requirements, since dev, allow caching
# hadolint ignore=DL3042
RUN pip install uvicorn==0.30.6 "litestar[standard]"==2.12.1 clickhouse_connect==0.7.19 confluent_kafka==2.3.0 pandas==2.2.3 sqlalchemy==2.0.35 psycopg2-binary==2.9.9

# Expose the port the app runs on
EXPOSE 8001

CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8001", "--reload"]


