FROM python:3.12-slim-bookworm

# Set the working directory
WORKDIR /app

# Install the requirements
RUN pip install --no-cache-dir uvicorn==0.34.0 "litestar[standard]"==2.15.1 clickhouse_connect==0.8.15 confluent_kafka==2.8.2 pandas==2.2.3 sqlalchemy==2.0.38 psycopg2-binary==2.9.10

COPY . /app

# Expose the port the app runs on
EXPOSE 8001

CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8001"]




