ARG ubuntu_release=24.04
ARG python_version=3.12.3
FROM ubuntu:${ubuntu_release} as base
FROM python:${python_version}

# Set the working directory
WORKDIR /app

# Install the requirements
RUN pip install --no-cache-dir --upgrade uvicorn==0.30.6 "litestar[standard]"==2.12.1 clickhouse_connect==0.7.19 confluent_kafka==2.3.0 pandas==2.2.3

COPY ./ /app/

# Expose the port the app runs on
EXPOSE 8001

CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8001", "--reload"]


