repos:
  ### PYTHON
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: [--fix]
  # Mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--namespace-packages, --explicit-package-bases]
        additional_dependencies: ['types-requests', 'pandas-stubs']

  ### DOCKER
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
  ### SHELL
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ['-x']
  ### JS / YML
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.1
    hooks:
      - id: prettier
        args: ['--config', '.prettierrc', '--ignore-unknown', '--write', '--check']
        language: node
        entry: node_modules/.bin/prettier
        require_serial: true
        files: ^(apps/.*\.(js|jsx|ts|tsx|css|svelte|yml))$
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.16.0
    hooks:
      - id: eslint
        name: eslint
        language: node
        entry: node_modules/eslint/bin/eslint.js
        #args: ['--fix'] #lets wait before using this
        require_serial: true
        files: \.(js|ts|svelte|css)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - svelte-eslint-parser
  - repo: local
    hooks:
      - id: svelte-check
        name: Svelte check
        language: system
        entry: npx svelte-check --fail-on-warnings
        files: \.(js|ts|svelte)$
        pass_filenames: false
        require_serial: true
  #- repo: https://github.com/sqlfluff/sqlfluff
  # Love SQLfluff, but causing huge issues with Clickhouse, many rules seem broken
  #rev: 3.2.0
  #hooks:
  #- id: sqlfluff-lint
  #args: [--dialect=clickhouse]
  #- id: sqlfluff-fix
  #args: [--dialect=clickhouse]
