site_name: Open Attribution
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
      - content.code.copy
  palette:
    scheme: slate
    primary: black

markdown_extensions:
  - attr_list
  - md_in_html

repo_url: https://github.com/ddxv/app-track
