
FROM python:3.12-slim-bookworm

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir --upgrade uvicorn==0.27.0.post1 "litestar[standard]"==2.5.3 confluent_kafka==2.3.0 clickhouse_connect==0.7.0 geoip2==4.8.1  "ua-parser[regex]"==1.0.0 pandas==2.2.3 sqlalchemy==2.0.35 psycopg2-binary==2.9.9

COPY . /app/

EXPOSE 8000

# Run the app with the Litestar CLI
CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8000"]


