
FROM python:3.12-slim-bookworm

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir --upgrade uvicorn==0.27.0.post1 "litestar[standard]"==2.5.3 confluent_kafka==2.3.0 clickhouse_connect==0.7.0 requests==2.32.3

COPY . /app/

EXPOSE 8000

# Run the app with the Litestar CLI
CMD ["python", "run_data_generation.py"]


