
FROM python:3.12-slim-bookworm

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir --upgrade uvicorn==0.34.0 "litestar[standard]"==2.15.1 confluent_kafka==2.8.2 clickhouse_connect==0.8.15 geoip2==5.0.1  "ua-parser[regex]"==1.0.1 pandas==2.2.3 sqlalchemy==2.0.38 psycopg2-binary==2.9.10

COPY . /app/

EXPOSE 8000

# Run the app with the Litestar CLI
CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8000"]


