# Usage
#   Start:          docker compose -f ~/open-attribution/docker/docker-compose.yml up -d
#   Down:           docker compose down
#   Stop:           docker compose stop
#   Pull New:           docker compose pull
#   Destroy:        docker compose -f ~/open-attribution/docker/docker-compose.yml down -v --remove-orphans

name: openattribution

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9.1
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper-volume:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.6.1
    container_name: kafka
    ports:
      - '9093:9093'
    volumes:
      - 'kafka-volume:/bitnami'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.1.1
    # image: openattribution/clickhouse:main
    healthcheck:
      test: ['CMD-SHELL', 'clickhouse-client --query "SELECT 1"']
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      - kafka
    ports:
      - '9000:9000'
      - '8123:8123'
    volumes:
      - ../sql/create/:/my-tables/
      - ../sql/startup-scripts/:/docker-entrypoint-initdb.d/
      - 'clickhouse-volume:/var/lib/clickhouse'
      - 'clickhouse-log-volume:/var/log/clickhouse-server'
  postback-api:
    container_name: postback-api
    build:
      context: ../
      dockerfile: docker/Dockerfile.python
    ports:
      - '8000:8000'
    depends_on:
      clickhouse:
        condition: service_healthy

  admin-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - 'pgdata-volume:/var/lib/postgresql/data'

  dash-backend:
    container_name: dash-backend
    build:
      # context: ../ # commented out, wasn't affecting volume?
      dockerfile: Dockerfile.dash-backend
    ports:
      - '8001:8001'
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    working_dir: /app
    depends_on:
      clickhouse:
        condition: service_healthy
      admin-db:
        condition: service_started
    volumes:
      - ../apps/dash-backend:/app

  dash-frontend:
    container_name: dash-frontend
    working_dir: /apps/dash-frontend
    command: npm run preview
    volumes:
      - ./apps/dash-frontend/src/:/apps/dash-frontend/src/
    build:
      context: ../
      dockerfile: docker/Dockerfile.dash-frontend
    ports:
      - '4173:4173'
    depends_on:
      - 'dash-backend'

volumes:
  # Persist across stop/start, not down
  kafka-volume:
  zookeeper-volume:
  clickhouse-log-volume:
  clickhouse-volume:
  pgdata-volume:
