# Usage
#   Start:          docker compose -f ~/open-attribution/docker/docker-compose.yml up -d
#   Down:           docker compose down
#   Stop:           docker compose stop
#   Pull New:           docker compose pull
#   Delete the clickhouse Kafka consumer, when clickhouse recreated will use any kafka logs: sudo docker exec -it kafka kafka-consumer-groups.sh --bootstrap-server localhost:9092 --delete --group clickhouse
#   Destroy:        docker compose -f ~/open-attribution/docker/docker-compose.yml down -v --remove-orphans

name: openattribution

services:
  kafka:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka
    ports:
      - '9093:9093'
    volumes:
      - 'kafka-volume:/bitnami'
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_RETENTION_HOURS=672
      - KAFKA_CFG_LOG_RETENTION_BYTES=10737418240 # 10GB, keep until official backup
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'kafka-topics.sh --bootstrap-server localhost:9092 --list']
      interval: 10s
      timeout: 5s
      retries: 3

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:24.11.5
    healthcheck:
      test: ['CMD-SHELL', 'clickhouse-client --query "EXISTS daily_overview" || exit 1']
      interval: 5s
      timeout: 5s
      retries: 15
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - '9000:9000'
      - '8123:8123'
    env_file:
      - .dev.env
    volumes:
      - ../apps/analytics-db/create/:/my-tables/
      - ../apps/analytics-db/startup-scripts/:/docker-entrypoint-initdb.d/
      - ../apps/analytics-db/config.xml:/etc/clickhouse-server/config.d/config.xml
      - 'clickhouse-volume:/var/lib/clickhouse'
      - 'clickhouse-log-volume:/var/log/clickhouse-server'

  postback-api:
    container_name: postback-api
    command: litestar run --host 0.0.0.0 --port 8000 --reload
    build:
      context: ../apps/postback-api
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - '8000:8000'
    env_file:
      - .dev.env
    depends_on:
      clickhouse:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --timeout=3 --tries=1 -qO- http://postback-api:8000/collect/health > /dev/null'
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../apps/postback-api:/app
      - 'postback-api-volume:/root/.config/geo-data'

  postback-test:
    container_name: postback-test
    build:
      context: ../apps/postback-api
      dockerfile: Dockerfile.test
    working_dir: /app
    command: bash -c "python run_data_generation.py -i && python run_data_generation.py"
    depends_on:
      postback-api:
        condition: service_healthy
    env_file:
      - .dev.env
    environment:
      - TEST_HOST=${TEST_HOST:-http://postback-api:8000}

  admin-db:
    container_name: admin-db
    image: postgres:17-bullseye
    restart: 'no'
    ports:
      - '5432:5432'
    env_file:
      - .dev.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - 'pgdata-volume:/var/lib/postgresql/data'
      - '../apps/admin-db/pg-init.sql:/docker-entrypoint-initdb.d/init.sql'

  dash-backend:
    container_name: dash-backend
    build:
      context: ../apps/dash-backend
      dockerfile: Dockerfile.dev
    ports:
      - '8001:8001'
    env_file:
      - .dev.env
    command: litestar run --host 0.0.0.0 --port 8001 --reload
    working_dir: /app
    depends_on:
      clickhouse:
        condition: service_healthy
      admin-db:
        condition: service_started
    volumes:
      - ../apps/dash-backend:/app

  dash-frontend:
    container_name: dash-frontend
    working_dir: /apps/dash-frontend
    command: npm run dev
    build:
      context: ../apps/dash-frontend
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    depends_on:
      - 'dash-backend'
    volumes:
      - ../apps/dash-frontend:/apps/dash-frontend
      - /apps/dash-frontend/node_modules

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      - DOZZLE_ENABLE_ACTIONS=true

volumes:
  # Persist across stop/start, not down
  kafka-volume:
  clickhouse-log-volume:
  clickhouse-volume:
  pgdata-volume:
  postback-api-volume:
