INHERIT: ../../mkdocsbase.yml
site_name: Open Attribution Docs

site_url: https://openattribution.dev/docs/

# This sets the export location as well as relative HTML links /documentation/todos
site_dir: ../../www/static/generated-docs/
docs_dir: '.'

nav:
  - Docs: index.md
  - TODO and Roadmap:
      - TODOs Overview: ./todo/todos.md
      - Dash: ./todo/dash.md
      - Batch Data Collection: ./todo/data_collection_batch.md
      - SDKs: ./todo/sdk.md
      - Database Overview: ./todo/database_overview.md
  - Getting Started:
      - Installation: ./getting_started/installation.md
      - Develop Locally: ./getting_started/develop_locally.md
  - About:
      - History: ./about/history.md
      - Target Use Cases: ./about/target_use_cases.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Admonitions are info/tip/warning boxes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/OpenAttribution/open-attribution
edit_uri: edit/main/apps/docs/

copyright: Copyright &copy; 2023 - Open Attribution LLC
