# Build for local development use and hot module reloading
# Build Stage
FROM node:20 as builder

WORKDIR /apps/dash-frontend

COPY package.json /apps/dash-frontend/
COPY package-lock.json /apps/dash-frontend/

RUN npm install

COPY ./ ./
RUN npm run build

EXPOSE 4173

CMD ["npm", "run", "preview"]
