INHERIT: ../../mkdocsbase.yml
site_name: Open Attribution Docs

site_url: https://openattribution.dev/blog/

# This sets the export location as well as relative HTML links /documentation/todos
site_dir: ../../www/static/generated-blog/
docs_dir: '.'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Admonitions are info/tip/warning boxes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

repo_url: https://github.com/OpenAttribution/open-attribution
edit_uri: edit/main/apps/docs/

copyright: Copyright &copy; 2023 - Open Attribution LLC
