# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image dash

on:
  # TODO: Should use releases instead of push?
  # release:
  # types: [published]
  push:
    branches: ['main']
    paths:
      - 'docker/Dockerfile.dash'
      - 'apps/shared/**'
      - 'apps/dash/**'
      # Publish semver tags as releases.
    tags: ['v*.*.*']

jobs:
  push_to_registry:
    if: github.repository_owner == 'OpenAttribution'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set OpenAttribution docker env
        run: |
          echo 'PUBLIC_SUPERSET_INSIDE_DOCKER_HOST="superset"' > apps/dash/.env
          echo 'PUBLIC_SUPERSET_BROWSER_HOST="https://openattribution.dev"' >> apps/dash/.env
          pwd
          cat apps/dash/.env

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: openattribution
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: openattribution/dash

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: docker/Dockerfile.dash
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
