name: Push Production Demo to Digital Ocean

on:
  push:
    branches:
      - main
    paths:
      - 'apps/superset/exported/**'
      - 'docker/docker-compose.yml'
  workflow_run:
    workflows: [Publish Docker image dash, Publish Docker image python API]
    # NOTE: Does this trigger when ALL workflows completed or just when EITHER?
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    if: github.repository_owner == 'OpenAttribution'
    name: Deploy on main branch push
    runs-on: ubuntu-latest
    environment: production-demo
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4
      - name: Deploy to my Droplet
        uses: appleboy/ssh-action@master
        env:
          TARGETDIR: open-attribution
        with:
          host: ${{ vars.HOST_DNS }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8807
          envs: TARGETDIR
          script_stop: true
          script: |
            cd $TARGETDIR
            pwd
            git pull origin main
            docker compose -f docker/docker-compose.yml down
            docker compose -f docker/docker-compose.yml pull
            docker compose -f docker/docker-compose.yml up -d
